.PHONY: clean All

All:
	@echo "----------Building project:[ markovcahin - Debug ]----------"
	@cd "markovcahin" && "$(MAKE)" -f  "markovcahin.mk"
clean:
	@echo "----------Cleaning project:[ markovcahin - Debug ]----------"
	@cd "markovcahin" && "$(MAKE)" -f  "markovcahin.mk" clean
