.PHONY: clean All

All:
	@echo "----------Building project:[ lists - Debug ]----------"
	@cd "lists" && "$(MAKE)" -f  "lists.mk"
clean:
	@echo "----------Cleaning project:[ lists - Debug ]----------"
	@cd "lists" && "$(MAKE)" -f  "lists.mk" clean
