.PHONY: clean All

All:
	@echo "----------Building project:[ deaw - Debug ]----------"
	@cd "deaw" && "$(MAKE)" -f  "deaw.mk"
clean:
	@echo "----------Cleaning project:[ deaw - Debug ]----------"
	@cd "deaw" && "$(MAKE)" -f  "deaw.mk" clean
