.PHONY: clean All

All:
	@echo "----------Building project:[ calculate - Debug ]----------"
	@cd "calculate" && "$(MAKE)" -f  "calculate.mk"
clean:
	@echo "----------Cleaning project:[ calculate - Debug ]----------"
	@cd "calculate" && "$(MAKE)" -f  "calculate.mk" clean
