.PHONY: clean All

All:
	@echo "----------Building project:[ trees - Debug ]----------"
	@cd "trees" && "$(MAKE)" -f  "trees.mk"
clean:
	@echo "----------Cleaning project:[ trees - Debug ]----------"
	@cd "trees" && "$(MAKE)" -f  "trees.mk" clean
