.PHONY: clean All

All:
	@echo "----------Building project:[ array - Debug ]----------"
	@cd "array" && "$(MAKE)" -f  "array.mk"
clean:
	@echo "----------Cleaning project:[ array - Debug ]----------"
	@cd "array" && "$(MAKE)" -f  "array.mk" clean
